version: 1.0.{build}
image: Visual Studio 2017
configuration: Release


build:
  verbosity: minimal


before_build:
  - cd .\src
  - nuget restore


##skip testing altogether (temporarily, then use runner)
test: off
